### ISSUE TITLE
Remove dependency on Guava

### ISSUE THREAD

**Issue by juanpedromoreno** [higherkindness/mu-scala#183]
`frees-rpc` relies on **gRPC**, which depends on `Guava` 0.19.0: https://github.com/grpc/grpc-java/blob/e7f2f1d/build.gradle#L104.

Would it be possible to shade all the uses of Guava in `gRPC`/`frees-rpc`?

**Comment by L-Lavigne** [comment]
Quick update on this ticket: shading with sbt turns out to be rather convoluted. The main sources of documentation are the [sbt-assembly](https://github.com/sbt/sbt-assembly) `readme`, this [blog post by Manu Zhang](https://manuzhang.github.io/2016/10/15/shading.html) and this [StackOverflow answer](https://stackoverflow.com/a/47974750). Basically it involves creating a shaded fat-jar project containing all dependencies that use Guava, then depending on that local jar in the main project build(s), without transitively depending on the shaded libs. None of the examples given seem to work out-of-the-box especially for a multi-project build with interdependencies, and publishing the shaded jars is a whole other topic.

My suggestion is for us _not_ to publish shaded artifacts in case some client project needs it, but rather for freestyle-using client projects that experience Guava conflicts to arrange their own shading of either the freestyle side or the other guava-importing side. We could show examples of this in our docs, although there wouldn't be much freestyle-specific in the process except for naming our guava-including dependencies. Unfortunately I haven't yet been able successfully perform shading in an example client project based on the sources I mentioned. If we do want to publish an example, I'd appreciate help from someone who has done so in the past. Thanks!

**Comment by cb372** [comment]
These days grpc-java depends on a pretty recent version of Guava (`28.2-android`, latest version is `29.0`). Can we close this?

**Comment by juanpedromoreno** [comment]
👍
