### ISSUE TITLE
Clients should remain Scala.js compatible

### ISSUE THREAD

**Issue by juanpedromoreno** [higherkindness/mu-scala#21]
We should split the `rpc` core in order to make the client part compatible with Scala.js.

**Comment by juanpedromoreno** [comment]
Interesting findings by @calvellido :)

https://github.com/frees-io/freestyle-opscenter-webclient/issues/17

**Comment by L-Lavigne** [comment]
@juanpedromoreno could you clarify how this issue relates to #73? Thanks!

**Comment by juanpedromoreno** [comment]
As we will be deriving HTTP services with its auto-derived clients, those will be Scala.js compatible, so likely this issue could be closed once we get the HTTP features.

**Comment by SemanticBeeng** [comment]
@juanpedromoreno, @raulraja is it correct to understand this task is about 
1. generating client code that compiles to `scalajs`
2. not necessarily generating full ~stubs~ for both `avro` and `protobuf`
3. clearly not about providing the actual runtime for execution of the stubs (for example `ScalaPB` is the only `scalajs` `GRPC` runtime I know)

Please advise in these respects and also what it is necessary to bridge the gap to become able to actually call `mu` services from web clients compiled with `scalajs`  over https, using either / both `avro` and `protobuf`.

**Comment by rafaparadela** [comment]
@SemanticBeeng Thanks for bringing all these questions up.
Under the context of all the issues labeled as [`http`](https://github.com/higherkindness/mu/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Ahttp+) we are implementing the auto derivation of HTTP server and HTTP client for a given schema/protocol. 
What this issue propose is, due to the http4s clients are compatible with scalajs,  the derivation of the this part should be in a diferent sbt module, and thus, those projects that are acting as Mu clients only need to add `mu-http-client` as a dependency, whose artifact must be compatible to scalajs.

Side note: We are not using ScalaPB to convert the idl into the http clients.

I hope this answers your questions.

**Comment by SemanticBeeng** [comment]
> http4s clients are compatible with scalajs

Thank you for following up.
So https://github.com/higherkindness/mu/issues/593 is "done" in this sense, then?

**Comment by juanpedromoreno** [comment]
Dup of https://github.com/higherkindness/mu-scala/issues/593
